"""Pydantic schemas for RKLlama API."""

from .common import (
    ErrorResponse,
    ModelDetails,
    ModelInfo,
    Options,
    UsageStats,
)
from .modelfile import (
    ModelfilePatchRequest,
    ModelfilePropertyName,
    ModelfilePropertyResponse,
    ModelfileResponse,
)
from .native import (
    NativeDeleteRequest,
    NativeDeleteResponse,
    NativeForceUnloadAllResponse,
    NativeLoadRequest,
    NativeLoadResponse,
    NativeModelsResponse,
    NativeUnloadAllResponse,
    NativeUnloadRequest,
    NativeUnloadResponse,
)
from .ollama import (
    ChatMessage,
    ChatRequest,
    ChatResponse,
    ChatStreamChunk,
    CreateRequest,
    CreateResponse,
    DeleteRequest,
    DeleteResponse,
    EmbeddingsRequest,
    EmbeddingsResponse,
    GenerateRequest,
    GenerateResponse,
    GenerateStreamChunk,
    LoadRequest,
    LoadResponse,
    ModelTag,
    PsResponse,
    PullProgress,
    PullRequest,
    PullResponse,
    PullSource,
    RunningModel,
    ShowRequest,
    ShowResponse,
    TagsResponse,
    UnloadRequest,
    UnloadResponse,
    VersionResponse,
)
from .openai import (
    OpenAIChatMessage,
    OpenAIChatRequest,
    OpenAIChatResponse,
    OpenAIChatStreamChunk,
    OpenAICompletionRequest,
    OpenAICompletionResponse,
    OpenAIEmbeddingRequest,
    OpenAIEmbeddingResponse,
    OpenAIImageRequest,
    OpenAIImageResponse,
    OpenAIModel,
    OpenAIModelList,
    OpenAISpeechRequest,
    OpenAITranscriptionRequest,
    OpenAITranscriptionResponse,
)

__all__ = [
    # Common
    "ModelDetails",
    "ModelInfo",
    "UsageStats",
    "ErrorResponse",
    "Options",
    # Ollama
    "ChatMessage",
    "ChatRequest",
    "ChatResponse",
    "ChatStreamChunk",
    "GenerateRequest",
    "GenerateResponse",
    "GenerateStreamChunk",
    "EmbeddingsRequest",
    "EmbeddingsResponse",
    "ShowRequest",
    "ShowResponse",
    "CreateRequest",
    "CreateResponse",
    "PullRequest",
    "PullResponse",
    "PullProgress",
    "PullSource",
    "DeleteRequest",
    "DeleteResponse",
    "LoadRequest",
    "LoadResponse",
    "UnloadRequest",
    "UnloadResponse",
    "TagsResponse",
    "PsResponse",
    "VersionResponse",
    "ModelTag",
    "RunningModel",
    # OpenAI
    "OpenAIChatMessage",
    "OpenAIChatRequest",
    "OpenAIChatResponse",
    "OpenAIChatStreamChunk",
    "OpenAICompletionRequest",
    "OpenAICompletionResponse",
    "OpenAIEmbeddingRequest",
    "OpenAIEmbeddingResponse",
    "OpenAIModel",
    "OpenAIModelList",
    "OpenAIImageRequest",
    "OpenAIImageResponse",
    "OpenAISpeechRequest",
    "OpenAITranscriptionRequest",
    "OpenAITranscriptionResponse",
    # Modelfile
    "ModelfilePropertyName",
    "ModelfilePropertyResponse",
    "ModelfileResponse",
    "ModelfilePatchRequest",
    # Native
    "NativeDeleteRequest",
    "NativeDeleteResponse",
    "NativeForceUnloadAllResponse",
    "NativeLoadRequest",
    "NativeLoadResponse",
    "NativeModelsResponse",
    "NativeUnloadAllResponse",
    "NativeUnloadRequest",
    "NativeUnloadResponse",
]
